services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hubspot-integrations-api
    ports:
      - "8080:8080"
      - "5005:5005"
    env_file:
      - .env
    networks:
      - rede-ngrok

  ngrok:
    image: ngrok/ngrok:latest
    command: http --domain=prompt-vervet-one.ngrok-free.app app:8080
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"
    networks:
      - rede-ngrok

networks:
  rede-ngrok:
    driver: bridge
